dist: trusty

language: python

python:
 - "2.7"


before_install:
 - sudo apt-get install software-properties-common -y
 - sudo add-apt-repository ppa:fenics-packages/fenics -y
 - sudo apt-get update -q
 - sudo apt-get install --no-install-recommends fenics -y
 - sudo apt-get dist-upgrade -y -q

install: python setup.py install --user

script: pytest


