dist: xenial

language: generic

before_install:
 # FEniCS
 - sudo apt-get install software-properties-common -y
 - sudo add-apt-repository ppa:fenics-packages/fenics -y
 - sudo apt-get update -q
 - sudo apt-get install --no-install-recommends fenics -y
 #  Pytest
 - sudo apt-get install python-pytest -y
 - sudo apt-get install python-logilab-common -y
 
install: python setup.py install --user

script: py.test


